import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { preview } from '../assets';
import { getRandomPrompt } from '../utils/index';
import { FormFiel, Loader } from '../components';

const CreatePost = () =>{
    const navigate = useNavigate();
    const [form, setForm] = useState({
        name: '',
        prompt: '',
        photo: '',
    });
    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">
                    Create
                </h1>

                <p className="font-extrabold text-[#666e75] text-[14px] max-w[500px]">
                    Create imaginative and visually stunning images generated by DALL-E AI
                </p>
            </div>
        </section>
    )
}

export default CreatePost
